### ISSUE TITLE
4 new crashing inputs

### ISSUE THREAD

**Issue by andrew-epstein** [pcrain/slippc#17]
Getting tired of copy/pasting all the info, I'm sure you can manage without it. I've just pushed them to my fork. Reproduced on both MacOS and Ubuntu.

**Comment by pcrain** [comment]
crash14.slp
  - OOB memory access parsing metadata
  - Dolphin plays the replay perfectly fine (metadata is non-essential to the replay)
  - Fixed by adding sanity checks for file size when parsing metadata
  - Also made parser throw a warning and continue rather than failing outright when failing to parse metadata

crash15.slp
  - OOB memory access parsing pre-frame event
  - Dolphin hangs a few frames into the replay
  - Fixed by moving the size check for events compared to remaining bytes in file to before the code for actually parsing events

crash16.slp
  - File size too small to be an actual replay, but the old parser assumed the size would be reasonable
  - Dolphin hangs immediately
  - Fixed by adding a size check before parsing

crash17.slp
  - Same issue and fix as crash16.slp

All fixed! :)
