### ISSUE TITLE
Bus error

### ISSUE THREAD

**Issue by andrew-epstein** [pcrain/slippc#6]
```AddressSanitizer:DEADLYSIGNAL
=================================================================
==74585==ERROR: AddressSanitizer: BUS on unknown address 0x61a1fffffff0 (pc 0x0001049b8a8e bp 0x7ffeeb24fdf0 sp 0x7ffeeb24fc40 T0)
    #0 0x1049b8a8d in slip::Parser::_parseEventDescriptions() parser.cpp:102
    #1 0x1049b5d9e in slip::Parser::_parse() parser.cpp:47
    #2 0x1049b531d in slip::Parser::load(char const*) parser.cpp:39
    #3 0x1049b0d07 in main main.cpp:29
    #4 0x7fff5e0793d4 in start (libdyld.dylib:x86_64+0x163d4)
```
As usual, the line numbers are gonna be off. The details are the same as before. I'll upload the files to my fork after I create all the issues. This one is `crash6.slp`.

**Comment by pcrain** [comment]
crash6.slp:
  - Integer undeflow error for event codes greater than 128 being interpreted as signed ints and cast as unsigned ints
  + Fixed by casting ev_code to uint8_t before using it

crash7.slp:
  - Incorrect / corrupt game start event size led to underallocating memory for storing frames
  + Fixed by checking we're not writing past the max computed frame

crash8.slp:
  - Encountered an unknown, uninitialized event code due to corrupt game start event size
  + Fixed by checking that the event actually has a defined size

crash9.slp:
  - Identical issue as in crash7.slp -> same fix

crash10.slp:
  - Identical issue as in crash7.slp -> same fix

crash11.slp:
  - Out of bounds memory access caused by player index being greater than 7
  + Fixed by adding a sanity check for player index

All fixed!

**Comment by andrew-epstein** [comment]
Wow, great! I don't have any more of this type of issue yet, but I'll start fuzzing the new code now. Out of curiosity, did you try these files in Dolphin as well? I enjoyed reading your descriptions of what Dolphin did with the last batch of inputs.

**Comment by pcrain** [comment]
I have not tried them in Dolphin honestly, though I can try a little later! I actually spent 2 hours running code through the afl-fuzzer myself and found 11 more crashes, so assuming you're using default settings, there shouldn't be any more fuzz related problems! :) Let me know if you find anything though.
